[buildscript.run]
env = { AR = "/usr/bin/ar", CC = "/usr/bin/cc", CRATE_CC_NO_DEFAULTS = "1", CXX = "/usr/bin/c++", PYTHONPATH = "$(location toolchains//:python-compat)" }
rustc_link_lib = true
rustc_link_search = true
