[project]
name = "sleek"
revision = "1.0"

[providers]
local = "keyring://"

[profiles.default]
BUILDBUDDY_API_KEY = { description = "BuildBuddy API key for Buck2 remote execution and caching", required = true, providers = ["local"] }
